### ISSUE TITLE
Regression testing

### ISSUE THREAD

**Issue by michaelblyons** [nuchi/sublime-from-cfg#1]
You could make some [syntax test files](https://www.sublimetext.com/docs/syntax.html#testing) to check that the `sublime-syntax` you create still assigns the scopes correctly. You can grab a CI workflow either from [SublimeHQ Packages](https://github.com/sublimehq/Packages/blob/master/.github/workflows/ci.yml) or from [a community GitHub Action](https://github.com/SublimeText/syntax-test-action).

Also consider separating the main source code from your syntax definition files and their output.

**Comment by nuchi** [comment]
> You could make some [syntax test files](https://www.sublimetext.com/docs/syntax.html#testing) to check that the `sublime-syntax` you create still assigns the scopes correctly. You can grab a CI workflow either from [SublimeHQ Packages](https://github.com/sublimehq/Packages/blob/master/.github/workflows/ci.yml) or from [a community GitHub Action](https://github.com/SublimeText/syntax-test-action).
> 
> Also consider separating the main source code from your syntax definition files and their output.

Thanks, these are both on my to-do! (well, not on the to-do list in my readme, but I do plan to do them)

**Comment by nuchi** [comment]
Added syntax test files.
